modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
issueTrackerURL = "https://github.com/Akkiruk/cobblecrew/issues"
license = "MPL-2.0"

[[mods]]
modId = "cobblecrew"
version = "${version}"
displayName = "CobbleCrew"
authors = "Akkiruk, Accieo"
description = '''
Put your Pokémon to work — in the pasture AND by your side. 92+ jobs across 9 categories, with party Pokémon support.
'''
logoFile = "assets/cobblecrew/icon.png"

[[dependencies.cobblecrew]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblecrew]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cobblecrew.mixins.json"
